### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mysterymath** [ilmenit/CC65-Advanced-Optimizations#5]
Hi, I'm one of the LLVM-MOS developers!

I'm looking into incorporating this into our integration test suite as a benchmark, but it looks like there isn't a license for this repo that would allow that usage. Would it be possible to add a suitable free/open source licensce to this repo?

**Comment by ilmenit** [comment]
Hi,
Great to see your effort with LLVM-MOS, really looking forward to use it in a next project. I added a MIT license so feel free to use it for the benchmarks.
